### ISSUE TITLE
Use the static Loop methods instead of a Driver instance

### ISSUE THREAD

**Issue by joshdifabio** [amphp/react-adapter#1]
If I were to use React components alongside an interop loop in my application I think I'd want the React loop adapter to call the static Loop methods, such as `Loop::onReadable()`, instead of being injected with an interop driver, so that I'd have the same scoping guarantees with React components as I would with other components. Did you already consider this?

**Comment by joshdifabio** [comment]
That said, I don't know what `run()` and `stop()` would do when taking such an approach.

**Comment by trowski** [comment]
I think a better way would be a function that provides an instance based on the current `Driver` instance stored in the global accessor. If the `Driver` instance is swapped, the function will return a different loop instance.

```php
namespace Amp\ReactAdapter;

use Amp\ReactAdapter;
use React\EventLoop\LoopInterface;

const LOOP_ADAPTER_IDENTIFIER = LoopInterface::class;

function loop(): LoopInterface {
    $loop = Loop::getState(LOOP_ADAPTER_IDENTIFIER);
    if ($loop) {
        return $loop;
    }
    
    $loop = new ReactAdapter(Loop::get());
    Loop::setState(LOOP_ADAPTER_IDENTIFIER, $loop);
    return $loop;
}
```

**Comment by kelunik** [comment]
Resolved via https://github.com/amphp/react-adapter/commit/442faabf729122a039a92456b7c5cc55ffe5bcf3.
