### ISSUE TITLE
Amphp v3 compatibility

### ISSUE THREAD

**Issue by enumag** [amphp/react-adapter#13]
I'm using a React-based library https://github.com/jakubkulhan/bunny in my Amphp application. I noticed that this library doesn't have a v3 branch yet. Does that mean that React libraries are not yet supported in v3 or that this adapter is somehow not necessary anymore? Or is there some other issue that makes such adapter impossible?

**Comment by kelunik** [comment]
It will be supported, but v3 is still under development, so not all libraries have braches for it, yet.

**Comment by rekryt** [comment]
I was able to start RatchetPHP with Revolt and react-adapter:
https://github.com/amphp/react-adapter/pull/15
https://github.com/Rekryt/ratchet-revolt-example

**Comment by kelunik** [comment]
We do have a `v3` branch now. A beta will follow soon.
