### ISSUE TITLE
Converting Amp promise to ReactPHP promise

### ISSUE THREAD

**Issue by mmenozzi** [amphp/react-adapter#4]
Hi,
I'm new to async development so this is more a question and not an issue.

I would like to create an HTTP server with https://github.com/reactphp/http which runs on the Amp loop. My HTTP server must return "Deferred Responses" (https://github.com/reactphp/http#deferred-response) because I would like to queue jobs in a Beanstalkd tube using https://github.com/amphp/beanstalk.

The problem is that I have no idea of how to do this. I'm able to create deferred responses, for example with this script:

```php
<?php

require 'vendor/autoload.php';

use Amp\Loop;
use Amp\ReactAdapter\ReactAdapter;
use Psr\Http\Message\ServerRequestInterface;
use React\Http\Response;
use React\Http\Server;
use React\Promise\Promise;

Loop::run(function () {
    $loop = ReactAdapter::get();

    $server = new Server(function (ServerRequestInterface $request) use ($loop) {
        return new Promise(function ($resolve, $reject) use ($loop) {
            $loop->addTimer(1.5, function() use ($resolve) {
                $response = new Response(
                    200,
                    array(
                        'Content-Type' => 'text/plain'
                    ),
                    "Hello world"
                );
                $resolve($response);
            });
        });
    });

    $socket = new React\Socket\Server(8080, $loop);
    echo "Server running at http://127.0.0.1:8080\n";
    $server->listen($socket);
});
```

The problem comes when I want to defer a response after that the Beanstalkd client `put` promise resolves with a job id. The Beanstalkd's `put` method returns an Amp `Promise` but the React's HTTP server wants an instance of a React's `PromiseInterface`. So how can I do this? Do I have to convert Amp promise to React promise? And if so, how?

Thank you for your help!

**Comment by kelunik** [comment]
Welcome to asynchronous PHP! We're totally fine with questions and discussions as issues. [There's an adapter you can use](https://github.com/umbri/amp-react-interop/blob/07bd8b24ca26c967b577dfb3977130bf426cd003/lib/functions.php#L26-L38) written by @umbri. Maybe we should add it as a package under @amphp?

Some notes to your current code: You don't need to `use()` the `$loop` if you're running on the Amp event loop. You can set the timer by using `Amp\Loop::delay()`.

In case you didn't know: You could also make use of our [Aerys](https://github.com/amphp/aerys) HTTP server instead of ReactPHP's implementation. This would completely avoid the need for any adaption.

**Comment by mmenozzi** [comment]
Thank you @kelunik I didn't know that there is an adapter for that!
I don't know if you should add @umbri package under @amphp but what can I say is that I tried to find an adapter like that before opening the issue and I didn't find anything. Maybe if it was under @amphp I would have found it.

I know Aerys and I give it a try but it does to much for my needs. I think that you already know it because you opened [a related issue](https://github.com/amphp/aerys/issues/158).

**Comment by kelunik** [comment]
We should probably link that from this package's README at least. Do you want to provide a PR for that?

We've already made good progress refactoring Aerys in the `0.8.x` branch. Before we release that, it will be split into multiple packages moving some things out. Any feedback on that is very much appreciated!

I'm currently writing my Bachelor's thesis, so my time is quite constrained. My guess would be that a release won't happen before May, but we haven't talked about any date, yet.

**Comment by mmenozzi** [comment]
Done https://github.com/amphp/react-adapter/pull/5.
I'll check the work on Aerys. Good luck with your thesis!

**Comment by kelunik** [comment]
Thanks!
